-- DROP
DROP TABLE IF EXISTS note_t;

CREATE TABLE note_t (
	note_no	  INT	AUTO_INCREMENT PRIMARY KEY,
	title		  VARCHAR(200)  NOT NULL,
	contents   TEXT			 NOT NULL,
	created_at DATETIME		 DEFAULT CURRENT_TIMESTAMP,
	hit		  INT				 DEFAULT 0
)
ENGINE=INNODB
DEFAULT CHARSET = UTF8MB4
COLLATE = UTF8MB4_GENERAL_CI;